version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=frota-leve
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=frota-leve-db
    volumes:
      - frota_level_pg_data:/bitnami/postgresql

volumes:
  frota_level_pg_data: